### ISSUE TITLE
Parser for WordPress hooks

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/code-reference#7]
@claudiosanches For hooks, isn't there an easy process to generate by parsing like previously done in ApiGen context. If some hooks get added then it has to be manually inserted currently right?

**Comment by claudiosanches** [comment]
I included the results from ApiGen, I'll work in a proper parse for PHPDoc now, but for now we are using the old results.

**Comment by claudiosanches** [comment]
I updated the title of this issue, so we can track the work of creating a new parser.
